# Generated by Django 3.2 on 2021-04-15 14:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20210415_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 14, 39, 30, 957761, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Like_Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction', models.CharField(choices=[('', 'Unset'), ('L', 'Like'), ('D', 'Dislike')], default='', max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post')),
            ],
        ),
    ]
