# Generated by Django 3.2 on 2021-04-15 14:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20210415_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 14, 52, 56, 528876, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='like_dislike',
            unique_together={('post', 'owner')},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
        ),
    ]
