# Generated by Django 3.2 on 2021-04-15 14:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210415_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 14, 53, 41, 551035, tzinfo=utc)),
        ),
    ]
