# Generated by Django 3.2 on 2021-04-15 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_post_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 15, 11, 39, 25832, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='like_dislike',
            unique_together=set(),
        ),
    ]
