# Generated by Django 3.2 on 2021-04-15 15:13

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_auto_20210415_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 15, 18, 52, 40990, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='like_dislike',
            unique_together={('post', 'owner')},
        ),
    ]
