# Generated by Django 3.2 on 2021-04-15 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_post_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 15, 41, 33, 511172, tzinfo=utc)),
        ),
    ]
