# Generated by Django 3.2 on 2021-04-15 15:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0016_alter_post_post_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_dislike',
            name='interaction',
            field=models.CharField(choices=[('U', 'Unset'), ('L', 'Like'), ('D', 'Dislike')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='like_dislike',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 16, 3, 36, 215281, tzinfo=utc)),
        ),
    ]
