# Generated by Django 3.2 on 2021-04-15 16:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20210415_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 16, 20, 2, 479919, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='like_dislike',
            unique_together=set(),
        ),
    ]
