# Generated by Django 3.2 on 2021-04-18 05:24

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0019_alter_post_post_expiration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like_Dislike',
            new_name='LikeDislike',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 5, 29, 10, 256149, tzinfo=utc)),
        ),
    ]
