# Generated by Django 3.2 on 2021-04-18 05:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20210418_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 5, 29, 43, 444565, tzinfo=utc)),
        ),
    ]
