# Generated by Django 3.2 on 2021-04-18 06:50

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_post_post_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likedislike',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 6, 55, 11, 933703, tzinfo=utc)),
        ),
    ]
