# Generated by Django 3.2 on 2021-04-19 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20210418_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_owner',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='interaction',
            field=models.CharField(choices=[('L', 'Like'), ('D', 'Dislike')], max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 14, 26, 25, 973047, tzinfo=utc)),
        ),
    ]
